# -*- coding: utf-8 -*-
"""Atividade 2 29/02/24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHStZnsExKIZ7irkCDFY2z-ie_pK3W-o

1 - Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

a=float(input('Insira uma nota entre 0 e 10: '))

while a<=0 or a>10:
  print('Nota inválida.')
  a=float(input('Insira uma nota entre 0 e 10: '))

"""2 - Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.

"""

nome=(input('Insira seu nome de usuário: '))
senha=(input('Insira sua senha: '))


while nome==senha:
  print('Nome e senha inseridos são iguais. Insira dados diferentes. \n')
  nome=str(input('Insira seu nome de usuário: '))
  senha=str(input('Insira sua senha: '))

"""3 - Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.


"""

print('Números um abaixo do outro:')
for i in range(1, 21):
  print(i)
print()
print('Números um ao lado do outro:')
for i in range(1, 21):
  print(i, end=' ')

"""4 - Faça um programa que leia 5 números e informe o maior número.

"""

maiornum=0
for i in range(1,6):
  num=float(input('Insira um número:'))
  if num > maiornum:
    maiornum = num

print('O maior número é:', maiornum)

"""5 - Faça um programa que leia 5 números e informe a soma e a média dos números.

"""

# soma é a variável que vai agrupar os valores inserido em cada partida do contador
soma=0

for i in range(0, 5):
   num=float(input('Digite um número:'))
  #Função do +=: usado para adicionar o valor à variável e atribuir o resultado de volta à mesma variável/ altera e atualiza.
   soma += num
media = soma/5
print('A média dos números é:', media)
print('A soma dos números é:', soma)

"""6 - Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.

"""

for i in range (1,51):
  if i%2 != 0:
    print(i)

"""7 - Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.
Altere o programa anterior para mostrar no final a soma dos números.
"""

a=int(input('Digite um número:'))
b=int(input('Digite um número:'))
soma=0

for i in range((a+1), b):
#o consecutivo do primeiro até chegar no segundo
  print(i)
  soma=soma+i
print(soma)

"""8 - Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:

Tabuada de 5:
5 X 1 = 5
5 X 2 = 10
...
5 X 10 = 50
"""

a = int(input('Digite um número entre 1 e 10: '))
if a > 10 or a < 1:
   print('Número inválido!')
else:
   print('Tabuada do', a, ':)')
for i in range (1, 11):
   print(f'{a} X {i} = {a*i}')

"""9 - Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem.


"""

#ESSE NÃO TÁ CERTO#.
a = int(input("Insira o valor base: "))
b = int(input("Insira o valor expoente: "))
c = a #conservando o valor de a em outra variável para mostrá-la depois
for i in range(b - 1): #b-1 identifica quantas vezes a se multiplicará,
    a *= a #o valor de a é atualizado multiplicando-o por si mesmo. Isso efetivamente eleva a ao quadrado.
print(f"{c} elevado a {b} é {a}.")

"""10 - Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

a = []
b = []
c = 0
d = []
e = 0
for i in range(10):
    a.append(int(input("Insira um número: ")))
    if a[i]%2 != 0:
        b.append(a[i])
        c += 1
    else:
        d.append(a[i])
        e += 1
if c > 0:
    print(f"{'O número ímpar inserido é:' if c == 1 else 'Os números ímpares inseridos são:'} {b}")
if e > 0:
    print(f"{'O número par inserido é:' if c == 1 else 'Os números pares inseridos são:'} {d}")

"""11 - A série de Fibonacci é formada pela seqüência 1,1,2,3,5,8,13,21,34,55,...

---

Faça um programa capaz de gerar a série até o n−ésimo termo.

"""

def serieDeFibonacci(n):
    serie = [1, 1]
    while len(serie) < n:
        serie.append(serie[-1] + serie[-2])
    return serie[:n]

print(f"Eis a série gerada até o n-ésimo termo: {serieDeFibonacci(int(input('Insira o valor do n-ésimo termo: ')))}")

"""12 - A série de Fibonacci é formada pela seqüência 0,1,1,2,3,5,8,13,21,34,55,... Faça um programa que gere a série até que o valor seja maior que 500."""

serie = [1, 1]
while serie[-1] <= 500:
    serie.append(serie[-1] + serie[-2])
print(f"Eis a série gerada até que o valor seja maior do que 500: \n {serie} ")

"""13 - Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120

"""

num=int(input('Digite um número:'))

for i in range(num-1, 1, -1):
  print(f"{a} * {i} = {a * i}")
  a *= i
  print(f"O valor {b} fatorado é {a}.")

a = int(input("Insira um valor: "))
b = a
for i in range(a - 1, 1, -1):
    print(f"{a} * {i} = {a * i}")
    a *= i
print(f"O valor {b} fatorado é {a}.")