# -*- coding: utf-8 -*-
"""Atividades - funções(04/03)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmS-7jCn1a54wmzTJQApXuSz73cStl7i

1 - Faça um programa para imprimir:
1
 2 2
 3 3 3
.....
 n n n n n n ... n


para um  informado pelo usuário. Use uma função que receba um valor  inteiro e imprima até a n-ésima linha.
"""

def imprimir_como_piramide(a):
    for i in range (1, a + 1): #percorrer de 1 até o parâmetro+1
        for j in range (i):
            print(i, end = "  ")
        print()
imprimir_como_piramide (10)

"""2 - Escreva uma função chamada fatorial que calcula o fatorial de um número inteiro fornecido como argumento."""

def fatorial(n):#determinando função

  if n == 0: #se o parâmetro vai ser igual a 0 dá erro(1)
    return 1

  else:
    result = n * fatorial(n-1)
    return result

fatorial(5)

"""3 - Escreva uma função chamada verifica_primo que verifica se um número é primo ou não e retorna True ou False."""

def verificar_primo (a):
    if a == 1:
        return False
    elif a > 1:
        for i in range(2, a):
            if a % i == 0:
                return False
        return True
print("O número é primo." if verificar_primo (3) else "O número não é primo.")

"""4 - Escreva uma função chamada inverte_string que aceita uma string como parâmetro e retorna a string invertida.

"""

def reverter_string (a):
    b = ""
    for i in range (len (a)): #o "len" é usado pq não é previamente determinada a quantd. de ciclos do contador
        b += a [-(i + 1)]
    return b
print(reverter_string(" J E S U S"))

"""5 - Escreva uma função chamada maior_valor que aceita uma lista de números como parâmetro e retorna o maior valor na lista.

"""

def maior_valor(a):
  return max(a) #ou
  print(f"O valor maximo é: {max(a)}")

maior_valor([10, 20, 30, 40, 50])

"""6 - Escreva uma função chamada conta_vogais que aceita uma string como parâmetro e retorna o número de vogais na string.

"""

def conta_vogais(string): #string é o parâmetro da função
    vogais = "aeiouAEIOUáéíóú"
    quantvogais = 0
    for i in string: #na posição i do contador ele vê o que tem na string
        if i in vogais: #na posição do contador em que houver vogais vai ser somado 1 a quantidade de vogais
            quantvogais += 1
    return quantvogais

print(conta_vogais('Testando código.'))

"""7 - Escreva uma função chamada soma_quadrados que aceita uma lista de números como parâmetro e retorna a soma dos quadrados desses números.

"""

a = [1, 2, 3, 4, 5]
def somar_quadrados (a):
    b = 0
    for i in range (len (a)): #o "len" é pq a quantidade de números que preenchem a lista é indeterminada
        b += a [i] ** 2 #a(lista) naquela referente posição do contador vai ficar ao quadrado
    return b
print(somar_quadrados (a))

"""8 - Escreva uma função chamada imprime_tabuada que aceita um número inteiro como parâmetro e imprime a tabuada desse número de 1 a 10.

"""

def imprimir_tabuada (a):
    for i in range (1,11):
        print(f"{a} X {i} = {a * i}")
imprimir_tabuada (5)