# -*- coding: utf-8 -*-
"""Atividade(listas) - 01/03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frvQFNRZbDawYlTRYfI7HXUDrb5uq-t7

**Atividade - listas(01/03)**

1 - Faça um Programa que peça a idade e a altura de 5 pessoas, armazene cada informação no seu respectivo vetor. Imprima a idade e a altura na ordem inversa a ordem lida.

---
"""

#Abrir a lista vazia
listaidades = []
listaalturas = []

#Coloca pra percorrer o vetor
for i in range(0, 5):
  idades = int(input('Digite a idade: '))
  alturas = float(input('Digite a altura: '))
  listaidades.append(idades)
  listaalturas.append(alturas)

listaidades.reverse()
print(f'Idades invertidas: {listaidades}')
listaalturas.reverse()
print(f'Alturas invertidas: {listaalturas}')

"""2 - Faça um Programa que leia um vetor A com 10 números inteiros, calcule e mostre a soma dos quadrados dos elementos do vetor.

"""

a = [] #lista aberta
s = 0

for i in range(10):
  a.append((int(input('Digite um número: ')))**2)
  s += a[i] #soma += a lista naquela posição do do contador
print('A soma dos quadrados dos valores digitados é: ', s)

lista = []
soma = 0

for i in range(0,10):
  vet=int(input('Digite um número:'))
  lista.append(vet)
  soma += list[i]**2

print('A soma dos quadrados dos elemntos do vetor é:', soma)

"""3 - Faça um Programa que leia dois vetores com 10 elementos cada. Gere um terceiro vetor de 20 elementos, cujos valores deverão ser compostos pelos elementos intercalados dos dois outros vetores.

"""

lista1=[]
lista2=[]
lista3=[]

for i in range(10):
  vetor1=int(input('Insira números para a primeira lista:'))
  lista1.append(vetor1)

for i in range(10):
  vetor2=int(input('Insira números para a segunda lista:'))
  lista2.append(vetor2)

for i in range(10):
  lista3.append(lista1[i])#lista(com o "append" que já deixou um número ao lado do outro) seguida do vetor referenciando a posição do contador
  lista3.append(lista2[i])

print('A terceira lista, com vetores intercalados é: ', lista3)

"""4 - Altere o programa anterior, intercalando 3 vetores de 10 elementos cada.

"""

lista1=[]
lista2=[]
lista3=[]
lista_intercalada=[]

for i in range(10):
  vetor1=int(input('Insira números para a primeira lista:'))
  lista1.append(vetor1)

for i in range(10):
  vetor2=int(input('Insira números para a segunda lista:'))
  lista2.append(vetor2)

for i in range(10):
  vetor3=int(input('Insira números para a terceira lista:'))
  lista3.append(vetor3)

for i in range(10):
  lista_intercalada.append(lista1[i])
  lista_intercalada.append(lista2[i])
  lista_intercalada.append(lista3[i])


print('A quarta lista, com vetores intercalados é: ', lista_intercalada)

"""5 - Foram anotadas as idades e alturas de 10 alunos. Faça um Programa que determine quantos alunos com mais de 13 anos possuem altura inferior à média de altura desses alunos.

"""

lista = []
lista_altura = []
num = 0
a = 0

for i in range(10):
    lista.append(int(input("Diga sua idade: ")))
    lista_altura.append(int(input("Diga sua altura: ")))
    if lista[i] > 13:
        num += lista_altura[i]
        a += 1
num /= a
a = 0
for i in range(10):
    if lista[i] > 13 and lista[i] < num:
        a += 1
print(f"A quantidade de alunos com mais de 13 anos com altura inferior à média é {a}")

listidades = []
listalturas = []
somaalt = 0
tot = 0

for i in range(10):
    idades = int(input('Digite a idade:'))
    listidades.append(idades)
    alturas = float(input('Digite a altura:'))
    listalturas.append(alturas)
    somaalt += alturas

mediaalt = somaalt / 10

for i in range(10):
if listidades[i] > 13 and listalturas[i] < mediaalt:
    tot += 1

print(f'A quantidade de alunos com mais de 13 anos que estão abaixo da média de altura é:', tot)

""" 10 - Faça um programa que peça 10 números inteiros, calcule e mostre a :quantidade de números pares e a quantidade de números impares."""

a = []
b = []
c = 0
d = []
e = 0
for i in range(10):
    a.append(int(input("Insira um número: ")))
    if a[i]%2 != 0:
        b.append(a[i])
        c += 1
    else:
        d.append(a[i])
        e += 1
if c > 0:
    print(f"{'O número ímpar inserido é:' if c == 1 else 'Os números ímpares inseridos são:'} {b}")
if e > 0:
    print(f"{'O número par inserido é:' if c == 1 else 'Os números pares inseridos são:'} {d}")

#Lógica: com um contador, percorrer 10 vetores, colocar o "append"; verificar se é ímpar, preencher uma lista com os ímpares e contar quanto estes são. E repete.